//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pk_Uppgift.FileReaderReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileReaderReference.FileReaderServiceSoap")]
    public interface FileReaderServiceSoap {
        
        // CODEGEN: Generating message contract since element name filename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadFile", ReplyAction="*")]
        Pk_Uppgift.FileReaderReference.ReadFileResponse ReadFile(Pk_Uppgift.FileReaderReference.ReadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Pk_Uppgift.FileReaderReference.ReadFileResponse> ReadFileAsync(Pk_Uppgift.FileReaderReference.ReadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadFile", Namespace="http://tempuri.org/", Order=0)]
        public Pk_Uppgift.FileReaderReference.ReadFileRequestBody Body;
        
        public ReadFileRequest() {
        }
        
        public ReadFileRequest(Pk_Uppgift.FileReaderReference.ReadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public ReadFileRequestBody() {
        }
        
        public ReadFileRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pk_Uppgift.FileReaderReference.ReadFileResponseBody Body;
        
        public ReadFileResponse() {
        }
        
        public ReadFileResponse(Pk_Uppgift.FileReaderReference.ReadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadFileResult;
        
        public ReadFileResponseBody() {
        }
        
        public ReadFileResponseBody(string ReadFileResult) {
            this.ReadFileResult = ReadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileReaderServiceSoapChannel : Pk_Uppgift.FileReaderReference.FileReaderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileReaderServiceSoapClient : System.ServiceModel.ClientBase<Pk_Uppgift.FileReaderReference.FileReaderServiceSoap>, Pk_Uppgift.FileReaderReference.FileReaderServiceSoap {
        
        public FileReaderServiceSoapClient() {
        }
        
        public FileReaderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileReaderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReaderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReaderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pk_Uppgift.FileReaderReference.ReadFileResponse Pk_Uppgift.FileReaderReference.FileReaderServiceSoap.ReadFile(Pk_Uppgift.FileReaderReference.ReadFileRequest request) {
            return base.Channel.ReadFile(request);
        }
        
        public string ReadFile(string filename) {
            Pk_Uppgift.FileReaderReference.ReadFileRequest inValue = new Pk_Uppgift.FileReaderReference.ReadFileRequest();
            inValue.Body = new Pk_Uppgift.FileReaderReference.ReadFileRequestBody();
            inValue.Body.filename = filename;
            Pk_Uppgift.FileReaderReference.ReadFileResponse retVal = ((Pk_Uppgift.FileReaderReference.FileReaderServiceSoap)(this)).ReadFile(inValue);
            return retVal.Body.ReadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pk_Uppgift.FileReaderReference.ReadFileResponse> Pk_Uppgift.FileReaderReference.FileReaderServiceSoap.ReadFileAsync(Pk_Uppgift.FileReaderReference.ReadFileRequest request) {
            return base.Channel.ReadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pk_Uppgift.FileReaderReference.ReadFileResponse> ReadFileAsync(string filename) {
            Pk_Uppgift.FileReaderReference.ReadFileRequest inValue = new Pk_Uppgift.FileReaderReference.ReadFileRequest();
            inValue.Body = new Pk_Uppgift.FileReaderReference.ReadFileRequestBody();
            inValue.Body.filename = filename;
            return ((Pk_Uppgift.FileReaderReference.FileReaderServiceSoap)(this)).ReadFileAsync(inValue);
        }
    }
}
