//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pk_Uppgift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonInInsts = new HashSet<PersonInInst>();
        }
        
        public Person(string Name, string Telefon, string Mail, string Work)
        {
            this.Name = Name;
            this.Telefon = Telefon;
            this.Mail = Mail;
            this.Work = Work;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Work { get; set; }
        public Nullable<int> RoomId { get; set; }
    
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonInInst> PersonInInsts { get; set; }
    }
}
