//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pk_Uppgift
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInInstitutionView
    {
        public int PersonId { get; set; }
        public int InstitutionId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string Work { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string PersonName { get; set; }
        public string BuildingName { get; set; }
        public int PersonInInstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public int BuildingId { get; set; }
        public string RoomNr { get; set; }
    }
}
