//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pk_Uppgift
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PkDbEntities : DbContext
    {
        public PkDbEntities()
            : base("name=PkDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonInInst> PersonInInsts { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<PersonInInstitutionView> PersonInInstitutionViews { get; set; }
    }
}
